OPENAI_API_KEY="sk-proj-YsWvncO6eoxbg7s4NUMvT3BlbkFJmr00mZqQO1MuQXPSzjZ6"
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="default"
