OPENAI_API_KEY="sk-gpttest-Zr8XbgWdr8ILB1zE5YGST3BlbkFJgl998XBIa4Ds1xgnEzxd"
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="default"
